# This sample config contains all fields supported by ravenML core and the keypoints regression plugin.
# Plugin specific configuration is located in the plugin field.

dataset: tinycygnusdistractors
overwrite_local: False
artifact_path: './artifacts'
ec2_policy: stop
metadata:
    created_by: Shahmir Masood
    comments: no thanks
plugin:
    keypoints: 20
    batch_size: 5
    cache_train_data: True
    prefetch_num_batches: 10
    crop_size: 224
    shuffle_buffer_size: 200
    model_init_weights: imagenet
    model_architecture: mbnv3
    excluded_imagesets: []

    bbox_expand_min: 1.25
    bbox_expand_max: 1.875
    # random_hue: 0.1
    random_saturation: [ 0.7, 1.3 ]
    random_brightness: 0.2
    random_contrast: [ 0.8, 1.2 ]
    # random_gaussian: 0.05
    random_jpeg: [ 75, 100 ]
    #real_image_dir: '/home/ubuntu/cygnus-real-filtered'
    phases:
        - optimizer: Adam
          optimizer_args: {}
          start_layer: input_1
          lr_schedule:
            - exp: 0
              lr: 0.001
              epoch: 75
            - exp: 0
              lr: 0.0001
              epoch: 150
            - exp: 0.05
              lr: 0.0001
              epoch: 225  # this is the total # of epochs

    pnp_focal_length: 1422.2222222
    dropout: 0.0
